/*
 * CommonJS, and the lint rule is disabled rather than satisfied — the same
 * constraint `withGameCategory.js` and `withReleaseSigning.js` record: Expo
 * loads config plugins with plain Node at prebuild, before any transform runs.
 */
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const fs = require('fs');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const path = require('path');

/**
 * Puts the app icon, in full colour, on the right of every Android notification.
 *
 * ## Android draws two icons, and only one of them can be the app icon
 *
 * The **small icon** — the one in the status bar and the notification header —
 * is alpha-only. Since API 21 the system discards every colour in it and
 * refills the shape with a single tint, so handing it a colour icon produces
 * the well-known white square. That slot is `assets/android-icon-monochrome.png`
 * and it has to be a silhouette; there is no way around it and it is not an
 * Expo limitation.
 *
 * The **large icon** is the square drawn beside the text, and it is an ordinary
 * bitmap: full colour, untinted. That is the one place a notification can show
 * what the launcher shows, which is what makes a notification recognisable at a
 * glance rather than by reading the app name.
 *
 * expo-notifications supports it natively — `ExpoNotificationBuilder` reads a
 * manifest meta-data key:
 *
 * ```kotlin
 * const val META_DATA_LARGE_ICON_KEY: String =
 *   "expo.modules.notifications.large_notification_icon"
 * ```
 *
 * Its own config plugin exposes `icon` and `color` for the small icon and stops
 * there, leaving the key unset and the slot empty. So this plugin sets it.
 *
 * ## What it does
 *
 * Copies `assets/notification-large-icon.png` into the generated
 * `android/app/src/main/res/drawable-nodpi/` and points the meta-data at it.
 *
 * `drawable-nodpi` rather than a density bucket on purpose: one 256px bitmap
 * serves every screen, and Android scales it to the ~64dp slot. Dropping it in
 * plain `drawable/` would make the system treat it as mdpi artwork and scale it
 * up four times on an xxxhdpi phone.
 *
 * **A plugin rather than an edit to `android/`.** Prebuild regenerates both the
 * manifest and the res tree, so an edit there survives until the next config
 * change and then silently disappears — the failure mode `withGameCategory.js`
 * exists for too.
 *
 * A missing source file is a hard error rather than a skip. The icon is
 * generated by `script/make-icons.sh` and committed; if it is absent something
 * is wrong with the checkout, and a notification quietly losing its icon is
 * exactly the kind of thing nobody notices until a screenshot.
 *
 * Android only. iOS has no equivalent — a notification there shows the app icon
 * automatically, which is why this problem does not exist on that platform.
 */
const SOURCE = 'assets/notification-large-icon.png';
const RES_DIR = 'android/app/src/main/res/drawable-nodpi';
const FILE_NAME = 'notification_large_icon.png';
const META_DATA_KEY = 'expo.modules.notifications.large_notification_icon';

module.exports = function withNotificationLargeIcon(config) {
  const withCopiedIcon = withDangerousMod(config, [
    'android',
    (mod) => {
      const root = mod.modRequest.projectRoot;
      const from = path.join(root, SOURCE);

      if (!fs.existsSync(from)) {
        throw new Error(
          `withNotificationLargeIcon: ${SOURCE} is missing. Run script/make-icons.sh.`
        );
      }

      const dir = path.join(root, RES_DIR);
      fs.mkdirSync(dir, { recursive: true });
      fs.copyFileSync(from, path.join(dir, FILE_NAME));
      return mod;
    },
  ]);

  return withAndroidManifest(withCopiedIcon, (mod) => {
    const application = mod.modResults.manifest.application?.[0];
    if (!application) return mod;

    application['meta-data'] ??= [];
    const existing = application['meta-data'].find(
      (entry) => entry.$['android:name'] === META_DATA_KEY
    );

    // The resource is named without its extension, the way a manifest refers to
    // any drawable.
    const resource = `@drawable/${FILE_NAME.replace(/\.png$/, '')}`;

    if (existing) {
      existing.$['android:resource'] = resource;
    } else {
      application['meta-data'].push({
        $: { 'android:name': META_DATA_KEY, 'android:resource': resource },
      });
    }

    return mod;
  });
};
