#!/usr/bin/env bash
#
# A release APK built from nothing, so a stale artefact cannot reach a tester.
#
# `npm run android:apk` on its own is incremental. Gradle is good at knowing
# what changed, and the places it is wrong are exactly the places that bite
# here: a regenerated `android/` from a config change, a JS bundle whose Metro
# cache predates a dependency bump, a resource that R8 shrank on a previous
# run. None of those fail loudly. They ship.
#
# So this throws away every layer it can and rebuilds them in order:
#
#   1. Metro and Expo caches      — the JS bundle's inputs
#   2. android/                   — regenerated by prebuild from app.config.ts
#   3. Gradle's build output      — dex, resources, previous APKs
#
# What it deliberately does NOT touch:
#
#   - node_modules. It is not a build cache; npm owns it, and reinstalling adds
#     minutes to every build to fix a problem that has never occurred here. Use
#     `--deps` on the rare occasion a dependency is genuinely suspect.
#   - The global Gradle cache in ~/.gradle. Shared with every other project on
#     the machine, and dropping it means re-downloading the whole Android
#     toolchain. `gradlew clean` covers this project's own output, which is the
#     part that goes stale.
#   - ios/. Same reasoning as the deps: this script builds an APK, and clearing
#     an unrelated platform's output is a surprise, not a service.
#
# Usage:
#   npm run build:apk                    arm64 only, the phones testers have
#   npm run build:aab                    the Play Store bundle, all ABIs
#   npm run build:apk -- --all           all four ABIs, roughly double the size
#   npm run build:apk -- --fast          incremental: no prebuild, no clean
#   npm run build:apk -- --deps          reinstall node_modules first
#   npm run build:apk -- --skip-checks   no lint/types/tests
#   npm run publish:apk                  build it, then upload it for testers
#   npm run build:apk -- --production    a store build: the `production` channel
#
# `--production` only changes which EAS Update channel the binary asks for. It
# is not a different build otherwise, and it is deliberately not implied by
# `--aab`: a bundle is also how a closed test is uploaded, and those testers
# should stay on `preview`.
#
# `publish:apk` is the same script with `--publish`, not a second pipeline. It
# builds exactly what `build:apk` builds — an unpublished build and a published
# one must never be able to differ, which is what a separate release script
# would eventually allow.
#
# `--fast` is the escape hatch and the reason the three older scripts
# (`android:apk`, `android:apk:all`, `android:aab`) are gone: each was this one
# with a piece missing, and the piece missing was always the cleaning. Reaching
# for a faster build should be a deliberate flag, not a differently named
# command that quietly skips the part that makes the build trustworthy.
#
set -euo pipefail

cd "$(dirname "$0")/.."

ARCHS="arm64-v8a"
RUN_CHECKS=1
CLEAN_DEPS=0
FAST=0
BUNDLE=0
PUBLISH=0
# The EAS Update channel this binary will ask for, read by `app.config.ts` and
# baked into the native project by prebuild.
#
# `preview` is the default and the default is the safe direction: a build that
# says nothing gets the tester channel, never the one real players are on.
# Publishing an update to `preview` reaches testers; promoting it to
# `production` afterwards is a server-side mapping change and needs no rebuild.
#
# Only a store build should carry `production`, and it has to be typed out.
CHANNEL=preview

for arg in "$@"; do
  case "$arg" in
    --all) ARCHS="" ;;
    --aab) BUNDLE=1 ;;
    --deps) CLEAN_DEPS=1 ;;
    --fast) FAST=1 ;;
    --skip-checks) RUN_CHECKS=0 ;;
    --publish) PUBLISH=1 ;;
    --production) CHANNEL=production ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

# A bundle is what Play serves, and it carries every ABI so Play can split them
# per device. Restricting it to arm64 would defeat the format.
if [ "$BUNDLE" -eq 1 ]; then ARCHS=""; fi

step() { printf '\n\033[36m▶ %s\033[0m\n' "$1"; }

# ---------------------------------------------------------------------------
# 0. The gates.
#
# Before the build, not after. A release APK that fails typecheck is a wasted
# ten minutes, and the commit hook cannot help here — a build is not a commit.
# ---------------------------------------------------------------------------
if [ "$RUN_CHECKS" -eq 1 ]; then
  step 'Checks'
  npm run check:all
fi

# ---------------------------------------------------------------------------
# 1. Caches that feed the JS bundle.
#
# Metro's transform cache lives in the system temp dir keyed by project, and it
# is the one that produces the strangest failures: a bundle built from a mix of
# old and new modules, which runs and is subtly wrong rather than crashing.
# ---------------------------------------------------------------------------
if [ "$FAST" -eq 0 ]; then
  step 'Clearing JS caches'
  rm -rf .expo node_modules/.cache
  rm -rf "${TMPDIR:-/tmp}"/metro-* "${TMPDIR:-/tmp}"/haste-map-* 2>/dev/null || true
fi

if [ "$CLEAN_DEPS" -eq 1 ]; then
  step 'Reinstalling dependencies'
  rm -rf node_modules
  npm ci
fi

# ---------------------------------------------------------------------------
# 2. The native project.
#
# `android/` is gitignored and generated, so regenerating it costs nothing and
# is the only way a change to `app.config.ts` — the icon, the splash, the R8
# flags, a plugin — is guaranteed to be in the build.
# ---------------------------------------------------------------------------
export DECANT_UPDATE_CHANNEL="$CHANNEL"
printf '\n  update channel: %s\n' "$CHANNEL"

if [ "$FAST" -eq 0 ]; then
  step 'Regenerating android/'
  rm -rf android
  npx expo prebuild --platform android --clean
elif [ ! -d android ]; then
  # --fast with nothing to be fast about. Prebuild anyway rather than fail on a
  # missing gradlew three lines later.
  step 'No android/ yet, generating it'
  npx expo prebuild --platform android
fi

# R8 strips what only reflection reaches, and that fails at runtime rather than
# at build time. Reanimated's keep rules arrive from its config plugin; if that
# ever stops happening, the APK builds green and crashes on the first animation.
if ! grep -q 'com.swmansion.reanimated' android/app/proguard-rules.pro 2>/dev/null; then
  printf '\n\033[33m⚠ Reanimated ProGuard rules missing from android/app/proguard-rules.pro.\033[0m\n'
  printf '  R8 may strip them. Play through a level before sharing this build.\n'
fi

# ---------------------------------------------------------------------------
# 3. Gradle.
#
# `clean` after a fresh prebuild looks redundant and is not: prebuild leaves any
# `android/.gradle` and `~/.gradle` state pointing at the old tree, and this is
# what forces the dex and the resource table to be rebuilt rather than reused.
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# 2b. The signing environment.
#
# Two failures cost a build each, both of them invisible in the error Gradle
# prints, so the script checks rather than hoping:
#
#   - A stale `DECANT_UPLOAD_STORE_FILE`. An exported variable outlives the
#     shell config that set it, so a terminal or an editor opened before the key
#     was renamed still carries the old path. `withReleaseSigning.js` ignores an
#     override whose file is missing; this drops it one step earlier so the
#     build log says the key was found rather than that an override was refused.
#
#   - A Gradle daemon holding an older environment. A daemon inherits the
#     environment of the shell that started it and keeps it for its whole life,
#     so a daemon born before the passwords were exported keeps signing with
#     what it had — and reports `keystore password was incorrect`, which sends
#     you to look at the keystore, which is fine. `--stop` costs one daemon
#     startup (~10s) against a three-minute build that fails at the last task.
#
# The password itself is never printed or written, only tested.
# ---------------------------------------------------------------------------
step 'Checking the signing environment'
if [ -n "${DECANT_UPLOAD_STORE_FILE:-}" ] && [ ! -f "$DECANT_UPLOAD_STORE_FILE" ]; then
  printf '  dropping stale DECANT_UPLOAD_STORE_FILE=%s (no such file)\n' "$DECANT_UPLOAD_STORE_FILE"
  unset DECANT_UPLOAD_STORE_FILE
fi

KEYSTORE="${DECANT_UPLOAD_STORE_FILE:-$PWD/decant-playstore.keystore}"
if [ -f "$KEYSTORE" ]; then
  if [ -z "${DECANT_UPLOAD_STORE_PASSWORD:-}" ] || [ -z "${DECANT_UPLOAD_KEY_PASSWORD:-}" ]; then
    echo "  $KEYSTORE is here but DECANT_UPLOAD_STORE_PASSWORD or DECANT_UPLOAD_KEY_PASSWORD is unset." >&2
    echo '  They live in ~/.zshrc; a non-interactive shell does not read it.' >&2
    exit 2
  fi
  # Fail here, in a second, rather than at `packageRelease` three minutes in.
  if ! keytool -list -keystore "$KEYSTORE" \
       -storepass "$DECANT_UPLOAD_STORE_PASSWORD" >/dev/null 2>&1; then
    echo "  DECANT_UPLOAD_STORE_PASSWORD does not open $KEYSTORE." >&2
    exit 2
  fi
  printf '  upload key ok: %s\n' "$KEYSTORE"
else
  printf '\n\033[33m⚠ No upload keystore. This build will be signed with the DEBUG key.\033[0m\n'
  printf '  Play rejects that. Put decant-playstore.keystore in the project root.\n'
fi

# A daemon carries the environment it was born with, including an older set of
# signing variables. Not needed with --fast, which is for a quick loop rather
# than for anything that leaves this machine.
if [ "$FAST" -eq 0 ]; then
  (cd android && ./gradlew --stop >/dev/null 2>&1) || true
fi

TASK=assembleRelease
KIND=APK
if [ "$BUNDLE" -eq 1 ]; then
  TASK=bundleRelease
  KIND=AAB
fi

step "Building release $KIND"
cd android
[ "$FAST" -eq 0 ] && ./gradlew clean

if [ -n "$ARCHS" ]; then
  ./gradlew "$TASK" -PreactNativeArchitectures="$ARCHS"
else
  ./gradlew "$TASK"
fi
cd ..

# ---------------------------------------------------------------------------
# 4. What came out.
#
# Printed because the debug APK's size means nothing and people compare the two
# — see the note in AGENTS.md. This one is the number that matters.
# ---------------------------------------------------------------------------
step 'Done'
if [ "$BUNDLE" -eq 1 ]; then
  find android/app/build/outputs/bundle -name '*.aab' -exec ls -lh {} \; |
    awk '{ printf "  %s  %s\n", $5, $NF }'
  printf '\n  Upload to Play. Play splits the ABIs, so a device downloads far less.\n'
else
  find android/app/build/outputs/apk/release -name '*.apk' -exec ls -lh {} \; |
    awk '{ printf "  %s  %s\n", $5, $NF }'
  printf '\n  Install with:  adb install -r <path above>\n'
fi

printf '  R8 is on in release. Play through a level before sharing.\n'

# Which key actually signed it, read off the artefact rather than inferred from
# the environment that built it. Gradle's own log says which config it chose;
# this says what came out, which is the thing an upload form checks.
#
# `keytool -printcert -jarfile` is the command everyone reaches for and it
# prints nothing here — these builds carry a v2 signature block, not a v1 JAR
# signature. apksigner reads both.
APKSIGNER=$(ls "${ANDROID_HOME:-$HOME/Library/Android/sdk}"/build-tools/*/apksigner 2>/dev/null | sort | tail -1 || true)
ARTEFACT=$([ "$BUNDLE" -eq 1 ] && echo '' || find android/app/build/outputs/apk/release -name '*.apk' | head -1)
if [ -n "$APKSIGNER" ] && [ -n "$ARTEFACT" ]; then
  printf '\n  Signed by:\n'
  "$APKSIGNER" verify --print-certs -v "$ARTEFACT" 2>/dev/null |
    grep -E 'certificate DN:|certificate SHA-1' |
    sed 's/^/    /'
fi

# ---------------------------------------------------------------------------
# 5. Publishing, if asked.
#
# One release, reused forever. Overwriting the asset inside a release tagged
# `latest` gives testers a page that never changes and always lists the current
# build:
#
#   https://github.com/<owner>/<repo>/releases
#
# **The releases page, not `/releases/latest/download/decant.apk`.** That direct
# link is the obvious one and it 404s here, for a reason that is easy to lose an
# afternoon to: GitHub's `/releases/latest` resolves to the newest release that
# is *not* a pre-release, and this one is created with `--prerelease`. A repo
# whose only release is a pre-release therefore has no "latest" at all, so both
# the page and the download shortcut under it are missing.
#
# Dropping `--prerelease` below would make the direct link work. It is kept
# because the badge is honest — this is a build for testers, not a store
# release — and one extra tap on the releases page is a smaller cost than a
# download URL that implies otherwise.
#
# `--clobber` is what makes the upload an overwrite rather than an error, and the
# release is created on first run if it is not there yet. Nothing here tags a
# commit: the tag is a bucket name, not a version, and moving it would rewrite
# history every build.
# ---------------------------------------------------------------------------
if [ "$PUBLISH" -eq 1 ]; then
  if [ "$BUNDLE" -eq 1 ]; then
    echo "refusing to publish an .aab — testers cannot install one" >&2
    exit 2
  fi

  command -v gh >/dev/null || { echo 'gh CLI not found: brew install gh' >&2; exit 2; }
  gh auth status >/dev/null 2>&1 || { echo 'gh not logged in: gh auth login' >&2; exit 2; }

  APK=$(find android/app/build/outputs/apk/release -name '*.apk' | head -1)
  [ -n "$APK" ] || { echo 'no APK to publish' >&2; exit 1; }

  # Renamed on upload. The asset name is the half of the download URL that has
  # to stay put, and Gradle's own `app-release.apk` says nothing about which app
  # it is once it is in someone's downloads folder.
  cp "$APK" "$PWD/decant.apk"

  step 'Publishing'
  if ! gh release view latest >/dev/null 2>&1; then
    gh release create latest \
      --title 'Latest test build' \
      --notes 'Rolling build for testers. Always the newest APK; the download link never changes.' \
      --prerelease
  fi

  gh release upload latest "$PWD/decant.apk" --clobber
  rm -f "$PWD/decant.apk"

  SLUG=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
  printf '\n  https://github.com/%s/releases\n' "$SLUG"
  printf '  Open that on an Android phone and tap decant.apk. Always this build.\n\n'
else
  printf '\n'
fi
