#!/usr/bin/env bash
#
# A release APK built from nothing, so a stale artefact cannot reach a tester.
#
# `npm run android:apk` on its own is incremental. Gradle is good at knowing
# what changed, and the places it is wrong are exactly the places that bite
# here: a regenerated `android/` from a config change, a JS bundle whose Metro
# cache predates a dependency bump, a resource that R8 shrank on a previous
# run. None of those fail loudly. They ship.
#
# So this throws away every layer it can and rebuilds them in order:
#
#   1. Metro and Expo caches      — the JS bundle's inputs
#   2. android/                   — regenerated by prebuild from app.config.ts
#   3. Gradle's build output      — dex, resources, previous APKs
#
# What it deliberately does NOT touch:
#
#   - node_modules. It is not a build cache; npm owns it, and reinstalling adds
#     minutes to every build to fix a problem that has never occurred here. Use
#     `--deps` on the rare occasion a dependency is genuinely suspect.
#   - The global Gradle cache in ~/.gradle. Shared with every other project on
#     the machine, and dropping it means re-downloading the whole Android
#     toolchain. `gradlew clean` covers this project's own output, which is the
#     part that goes stale.
#   - ios/. Same reasoning as the deps: this script builds an APK, and clearing
#     an unrelated platform's output is a surprise, not a service.
#
# Usage:
#   npm run build:apk                    arm64 only, the phones testers have
#   npm run build:aab                    the Play Store bundle, all ABIs
#   npm run build:apk -- --all           all four ABIs, roughly double the size
#   npm run build:apk -- --fast          incremental: no prebuild, no clean
#   npm run build:apk -- --deps          reinstall node_modules first
#   npm run build:apk -- --skip-checks   no lint/types/tests
#
# `--fast` is the escape hatch and the reason the three older scripts
# (`android:apk`, `android:apk:all`, `android:aab`) are gone: each was this one
# with a piece missing, and the piece missing was always the cleaning. Reaching
# for a faster build should be a deliberate flag, not a differently named
# command that quietly skips the part that makes the build trustworthy.
#
set -euo pipefail

cd "$(dirname "$0")/.."

ARCHS="arm64-v8a"
RUN_CHECKS=1
CLEAN_DEPS=0
FAST=0
BUNDLE=0

for arg in "$@"; do
  case "$arg" in
    --all) ARCHS="" ;;
    --aab) BUNDLE=1 ;;
    --deps) CLEAN_DEPS=1 ;;
    --fast) FAST=1 ;;
    --skip-checks) RUN_CHECKS=0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

# A bundle is what Play serves, and it carries every ABI so Play can split them
# per device. Restricting it to arm64 would defeat the format.
if [ "$BUNDLE" -eq 1 ]; then ARCHS=""; fi

step() { printf '\n\033[36m▶ %s\033[0m\n' "$1"; }

# ---------------------------------------------------------------------------
# 0. The gates.
#
# Before the build, not after. A release APK that fails typecheck is a wasted
# ten minutes, and the commit hook cannot help here — a build is not a commit.
# ---------------------------------------------------------------------------
if [ "$RUN_CHECKS" -eq 1 ]; then
  step 'Checks'
  npm run check:all
fi

# ---------------------------------------------------------------------------
# 1. Caches that feed the JS bundle.
#
# Metro's transform cache lives in the system temp dir keyed by project, and it
# is the one that produces the strangest failures: a bundle built from a mix of
# old and new modules, which runs and is subtly wrong rather than crashing.
# ---------------------------------------------------------------------------
if [ "$FAST" -eq 0 ]; then
  step 'Clearing JS caches'
  rm -rf .expo node_modules/.cache
  rm -rf "${TMPDIR:-/tmp}"/metro-* "${TMPDIR:-/tmp}"/haste-map-* 2>/dev/null || true
fi

if [ "$CLEAN_DEPS" -eq 1 ]; then
  step 'Reinstalling dependencies'
  rm -rf node_modules
  npm ci
fi

# ---------------------------------------------------------------------------
# 2. The native project.
#
# `android/` is gitignored and generated, so regenerating it costs nothing and
# is the only way a change to `app.config.ts` — the icon, the splash, the R8
# flags, a plugin — is guaranteed to be in the build.
# ---------------------------------------------------------------------------
if [ "$FAST" -eq 0 ]; then
  step 'Regenerating android/'
  rm -rf android
  npx expo prebuild --platform android --clean
elif [ ! -d android ]; then
  # --fast with nothing to be fast about. Prebuild anyway rather than fail on a
  # missing gradlew three lines later.
  step 'No android/ yet, generating it'
  npx expo prebuild --platform android
fi

# R8 strips what only reflection reaches, and that fails at runtime rather than
# at build time. Reanimated's keep rules arrive from its config plugin; if that
# ever stops happening, the APK builds green and crashes on the first animation.
if ! grep -q 'com.swmansion.reanimated' android/app/proguard-rules.pro 2>/dev/null; then
  printf '\n\033[33m⚠ Reanimated ProGuard rules missing from android/app/proguard-rules.pro.\033[0m\n'
  printf '  R8 may strip them. Play through a level before sharing this build.\n'
fi

# ---------------------------------------------------------------------------
# 3. Gradle.
#
# `clean` after a fresh prebuild looks redundant and is not: prebuild leaves any
# `android/.gradle` and `~/.gradle` state pointing at the old tree, and this is
# what forces the dex and the resource table to be rebuilt rather than reused.
# ---------------------------------------------------------------------------
TASK=assembleRelease
KIND=APK
if [ "$BUNDLE" -eq 1 ]; then
  TASK=bundleRelease
  KIND=AAB
fi

step "Building release $KIND"
cd android
[ "$FAST" -eq 0 ] && ./gradlew clean

if [ -n "$ARCHS" ]; then
  ./gradlew "$TASK" -PreactNativeArchitectures="$ARCHS"
else
  ./gradlew "$TASK"
fi
cd ..

# ---------------------------------------------------------------------------
# 4. What came out.
#
# Printed because the debug APK's size means nothing and people compare the two
# — see the note in AGENTS.md. This one is the number that matters.
# ---------------------------------------------------------------------------
step 'Done'
if [ "$BUNDLE" -eq 1 ]; then
  find android/app/build/outputs/bundle -name '*.aab' -exec ls -lh {} \; |
    awk '{ printf "  %s  %s\n", $5, $NF }'
  printf '\n  Upload to Play. Play splits the ABIs, so a device downloads far less.\n'
else
  find android/app/build/outputs/apk/release -name '*.apk' -exec ls -lh {} \; |
    awk '{ printf "  %s  %s\n", $5, $NF }'
  printf '\n  Install with:  adb install -r <path above>\n'
fi

printf '  R8 is on in release. Play through a level before sharing.\n\n'
