#!/usr/bin/env python3
"""
Frame the raw device captures as Play Store screenshots.

    python3 script/make-store-screenshots.py

Reads `store/captures/*.png` and writes `store/play/screenshots/play-NN.png`,
1080x1920 each — Play wants 9:16 or 16:9, and a phone framebuffer is neither
(iPhone 17 Pro is 1206x2622, a 9:19.6 slab). A plain resize would letterbox or
crop the board, so the capture is inset on the feature graphic's own background
with a caption above it.

**The captures are the masters and cannot be regenerated by a script.** They
came off a booted simulator with a human — or a cursor — playing the game, so
they are committed rather than derived. Everything below them is.

Two crops are deliberate. `CROP_TOP` clears the dynamic island, which otherwise
peeks over the top edge of the inset and reads as a rendering fault; `CROP_BOTTOM`
takes the home indicator. Between them they also remove every iOS tell, so the
same plates are honest on a Play listing.

The palette is copied from `src/theme/colors.ts` rather than imported — this is
Python and that is TypeScript. Move a color there and move it here too; nothing
tests this, because nothing in the app reads these files.
"""

import pathlib
from PIL import Image, ImageDraw, ImageFont, ImageFilter

ROOT = pathlib.Path(__file__).resolve().parent.parent
CAPTURES = ROOT / 'store' / 'captures'
OUT = ROOT / 'store' / 'play' / 'screenshots'

W, H = 1080, 1920

# From `colours` in src/theme/colors.ts.
NIGHT, NIGHT_DEEP = (0x2E, 0x1A, 0x5E), (0x14, 0x0A, 0x32)
LAMP, PLUM = (0xFF, 0xBE, 0x64), (0xA2, 0x4D, 0xFF)
GOLD_PALE, GOLD, GOLD_BRONZE = (0xFF, 0xEF, 0xB4), (0xFF, 0xD1, 0x70), (0xE7, 0xA3, 0x2E)

CROP_TOP, CROP_BOTTOM = 196, 52
CAPTION_Y = 170

# Order matters more than the captions do: Play shows two or three plates before
# anyone scrolls, and those drive the conversion rate that feeds ranking. The
# board goes first because it is the only one that says what the game *is*.
PLATES = [
    ('03-brew.png', 'Pour, sort, unwind'),
    ('01-board-mid.png', 'No timers. No fails.'),
    ('05-complete.png', 'Play it well, earn the stars'),
    ('04-stages.png', 'Thousands of puzzles'),
    ('06-rewards.png', 'A new brew every day'),
    ('01-home.png', 'Made for the ten quiet minutes'),
    ('08-colorblind.png', 'Colorblind marks on every vial'),
    ('07-shop.png', 'Vials worth playing toward'),
]

FONT_CANDIDATES = [
    '/System/Library/Fonts/Avenir Next.ttc',
    '/System/Library/Fonts/Supplemental/Futura.ttc',
    '/System/Library/Fonts/Helvetica.ttc',
]


def font(size):
    """A system face. Poppins is bundled in `assets/`, not installed, so PIL
    cannot resolve it by name — the caption is close in character, not identical."""
    for path in FONT_CANDIDATES:
        if pathlib.Path(path).exists():
            try:
                return ImageFont.truetype(path, size, index=1)
            except Exception:
                pass
    return ImageFont.load_default()


def ground():
    """The feature graphic's background, so the two read as one set."""
    bg = Image.new('RGB', (W, H))
    draw = ImageDraw.Draw(bg)
    for y in range(H):
        t = y / H
        draw.line([(0, y), (W, y)], fill=tuple(
            int(NIGHT[i] + (NIGHT_DEEP[i] - NIGHT[i]) * t) for i in range(3)))

    def glow(cx, cy, radius, color, peak):
        layer = Image.new('L', (W, H), 0)
        ld = ImageDraw.Draw(layer)
        steps = 26
        for i in range(steps, 0, -1):
            r = radius * i / steps
            ld.ellipse([cx - r, cy - r, cx + r, cy + r],
                       fill=int(peak * 255 * (1 - i / steps) ** 2))
        bg.paste(Image.new('RGB', (W, H), color), (0, 0),
                 layer.filter(ImageFilter.GaussianBlur(90)))

    glow(W * 0.16, H * 0.05, W * 1.00, LAMP, 0.26)
    glow(W * 0.92, H * 1.02, W * 0.95, PLUM, 0.30)
    return bg


def gold_caption(canvas, text, f):
    """Gradient lettering, the same ramp `gradients.wordmark` uses. Flat gold
    reads as a label; the ramp reads as the game's own chrome."""
    draw = ImageDraw.Draw(canvas)
    box = draw.textbbox((W // 2, CAPTION_Y), text, font=f, anchor='mm')
    height = box[3] - box[1]
    if height <= 0:
        return

    mask = Image.new('L', (W, H), 0)
    ImageDraw.Draw(mask).text((W // 2, CAPTION_Y), text, font=f,
                              anchor='mm', fill=255)

    grad = Image.new('RGB', (W, H))
    gd = ImageDraw.Draw(grad)
    for y in range(box[1], box[3]):
        t = (y - box[1]) / max(height - 1, 1)
        a, b = (GOLD_PALE, GOLD) if t < 0.5 else (GOLD, GOLD_BRONZE)
        k = t * 2 if t < 0.5 else (t - 0.5) * 2
        gd.line([(0, y), (W, y)],
                fill=tuple(int(a[i] + (b[i] - a[i]) * k) for i in range(3)))

    canvas.paste(grad, (0, 0), mask)


def rounded(img, radius):
    mask = Image.new('L', img.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        [0, 0, img.size[0] - 1, img.size[1] - 1], radius=radius, fill=255)
    out = img.convert('RGBA')
    out.putalpha(mask)
    return out


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for index, (source, caption) in enumerate(PLATES, 1):
        path = CAPTURES / source
        if not path.exists():
            print(f'  missing {source} — skipped')
            continue

        canvas = ground()
        gold_caption(canvas, caption, font(56))

        shot = Image.open(path).convert('RGB')
        shot = shot.crop((0, CROP_TOP, shot.width, shot.height - CROP_BOTTOM))

        top = CAPTION_Y + 128
        available = H - top - 92
        width = int(shot.width * (available / shot.height))
        height = available
        if width > W - 186:
            width = W - 186
            height = int(shot.height * (width / shot.width))
        shot = rounded(shot.resize((width, height), Image.LANCZOS), 44)

        x, y = (W - width) // 2, top

        # A drop shadow, so the plate sits on the ground rather than in it.
        shadow = Image.new('RGBA', (W, H), (0, 0, 0, 0))
        ImageDraw.Draw(shadow).rounded_rectangle(
            [x + 8, y + 14, x + width + 8, y + height + 14],
            radius=44, fill=(0, 0, 0, 150))
        shadow = shadow.filter(ImageFilter.GaussianBlur(26))
        canvas.paste(Image.new('RGB', (W, H), (0, 0, 0)), (0, 0),
                     shadow.split()[3])

        canvas.paste(shot, (x, y), shot)
        out = OUT / f'play-{index:02d}.png'
        canvas.save(out)
        print(f'  {out.relative_to(ROOT)}  <- {source}')


if __name__ == '__main__':
    main()
